import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { MetaSolverStrategyGeneratedModule, MetaSolverStrategyGeneratedSharedModule } from './generated/module.js';
import { MetaSolverStrategyValidator, registerValidationChecks } from './meta-solver-strategy-validator.js';
import { MetaSolverStrategyCompletionsProvider } from './meta-solver-strategy-completions-provider.js';
import { MetaSolverStrategyHoverProvider } from "./meta-solver-strategy-hover-provider.js";

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MetaSolverStrategyAddedServices = {
    validation: {
        MetaSolverStrategyValidator: MetaSolverStrategyValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MetaSolverStrategyServices = LangiumServices & MetaSolverStrategyAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MetaSolverStrategyModule: Module<MetaSolverStrategyServices, PartialLangiumServices & MetaSolverStrategyAddedServices> = {
    validation: {
        MetaSolverStrategyValidator: () => new MetaSolverStrategyValidator()
    },
    lsp: {
        HoverProvider: (services) => new MetaSolverStrategyHoverProvider(services),
        CompletionProvider: (services) => new MetaSolverStrategyCompletionsProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMetaSolverStrategyServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    MetaSolverStrategy: MetaSolverStrategyServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MetaSolverStrategyGeneratedSharedModule
    );
    const MetaSolverStrategy = inject(
        createDefaultModule({ shared }),
        MetaSolverStrategyGeneratedModule,
        MetaSolverStrategyModule
    );
    shared.ServiceRegistry.register(MetaSolverStrategy);
    registerValidationChecks(MetaSolverStrategy);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, MetaSolverStrategy };
}
